### ISSUE TITLE
Issue with PSD calculation

### ISSUE THREAD

**Issue by cliffckerr** [suny-downstate-medical-center/netpyne#443]
There seems to be an issue with the PSD calculation for 0.9.3 vs. 0.9.2. For 0.9.2, it seems to be calculating the spectrum correctly (within the limits of finite time windows etc.). However, with the new version, even relatively uniform rasters result in PSDs like this:

![image](https://user-images.githubusercontent.com/3239256/65207170-b4a7b880-da45-11e9-828e-f7570ea11a0d.png)

**Comment by jchen6727** [comment]
Hello, I am working on correcting bugs specific to running NetPyNE on Windows OS (or Linux distributions)
Was the issue causing this resolved? Within NetPyNE 1.0.3.1?
If not, can you please briefly elaborate -- what script were you running. what was the expected outcome -- so that I can try to help?
Many thanks,
